export const ProjectList = [
    {
        id: 1,
        name: 'Portfolio',
        desc: 'Portfolio website made with React to showcase my projects and skills.',
        techstack: 'React',
        date: '2021',
        img : './projects/portfolio-phone.png',
        imgLaptop : './projects/portfolio-laptop.png',
        imgPC : './projects/portfolio-pc.png',
        repo_name: 'portfolio',
        live: 'https://koppanydavid.hu',
    },
    {
        id: 2,
        name: 'E-commerce',
        desc: 'E-commerce app made width React and Redux. Work in progress.',
        techstack: 'React/Redux',
        date: '2021',
        img : './projects/ecommerce-phone.png',
        imgLaptop : './projects/portfolio-laptop.png',
        imgPC : './projects/portfolio-pc.png',
        repo_name: 'ecommerce-react-redux',
        live: 'https://kdavid-react-redux-ecommerce.netlify.app/',
    },
    {
        id: 3,
        name: 'Baranyi Épületvillamosság',
        desc: 'Website made with react, to help the company engage with potential customers. Work in progress',
        techstack: 'React',
        date: '2021',
        img : './projects/baranyi-phone.png',
        imgLaptop : './projects/baranyi-laptop.png',
        imgPC : './projects/baranyi-pc.png',
        repo_name: 'baranyi_epuletvillamossag',
        live: 'https://baranyiepuletvillamossag.netlify.app/',
    },
    {
        id: 4,
        name: 'Communication',
        desc: <div>Application for communication between doctors and clients. <br/>You can try it out with the following credentials:<br/>Username : admin@admin.hu <br/>Password : admin123</div>,
        techstack: 'Angular/Firebase',
        date: '2021',
        img : './projects/communication-phone.png',
        imgLaptop : './projects/portfolio-laptop.png',
        imgPC : './projects/portfolio-pc.png',
        repo_name: 'webkert-communication',
        live: 'https://webkert-4b250.web.app/',
    },
]
