export const ProjectList = [
    {
        id: 1,
        name: 'Portfolio',
        desc: 'Portfolio website made with React to showcase my projects and skills.',
        techstack: 'React',
        date: '2021',
        img : './img/appointments.webp',
        repo_name: 'portfolio',
        live: 'https://koppanydavid.netlify.app',
    },
    {
        id: 2,
        name: 'Communication',
        desc: 'Application for communication between doctors and clients.',
        techstack: 'Angular/Firebase',
        date: '2021',
        img : './img/appointments.webp',
        repo_name: 'webkert-communication',
        live: 'https://webkert-4b250.web.app/',
    },
    {
        id: 3,
        name: 'E-commerce',
        desc: 'E-commerce app made width React and Redux. Work in progress.',
        techstack: 'React/Redux',
        date: '2021',
        img : './img/bookstore.jpg',
        repo_name: 'ecommerce-react-redux',
        live: 'https://kdavid-react-redux-ecommerce.netlify.app/',
    },
]
