export const links = [
    /*{
        id:1,
        text:'about',
        url:'#about'
    },*/
    {
        id:1,
        text:'projects',
        url:'#projects'
    },
    {
        id:2,
        text:'education',
        url:'#education'
    },
    {
        id:3,
        text:'contact',
        url:'#contact'
    },
]